### ISSUE TITLE
"node has no valid x or y position. Expecting a number."

### ISSUE THREAD

**Issue by Melkaz** [graphology/graphology-svg#2]
```javascript
const Graph = require('graphology');
var render = require("graphology-svg");

const graph = new Graph();
graph.addNode('John');
graph.addNode('Martha');
graph.addEdge('John', 'Martha');

render(graph, "./graph.svg", () => console.log("Done!"));
```

It gives me this error:

```
Error: graphology-svg: the "John" node has no valid x or y position. Expecting a number.
    at Object.exports.DEFAULT_NODE_REDUCER (/home/runner/NoisySilverTelecommunications/node_modules/graphology-svg/defaults.js:29:11)
    at /home/runner/NoisySilverTelecommunications/node_modules/graphology-svg/helpers.js:25:21
    at /home/runner/NoisySilverTelecommunications/node_modules/graphology/dist/graph.js:1430:
7    at Map.forEach (<anonymous>)
    at Graph.forEachNode (/home/runner/NoisySilverTelecommunications/node_modules/graphology/dist/graph.js:1429:17)
    at Object.reduceNodes (/home/runner/NoisySilverTelecommunications/node_modules/graphology-svg/helpers.js:20:9)
    at renderer (/home/runner/NoisySilverTelecommunications/node_modules/graphology-svg/renderer.js:30:26)
    at render (/home/runner/NoisySilverTelecommunications/node_modules/graphology-svg/index.j
s:19:28)
    at /home/runner/NoisySilverTelecommunications/index.js:9:1
```

Running code here: https://repl.it/repls/NoisySilverTelecommunications

Thanks !

**Comment by Yomguithereal** [comment]
Hello @Melkaz,
This is to be expected because `grapholog-svg` needs to know the positions of your nodes to render them at the correct place. It has no opinion on how you should layout them.

The solution is therefore to apply a layout algorithm to your graph to give a position to your nodes. You can for instance use the [`graphology-layout-forceatlas2`](https://github.com/graphology/graphology-layout-forceatlas2#synchronous-layout) library to do so (use the `inferSettings` method for a quick and easy way to configure the layout).
